(define (problem aa-combo-1)
 (:domain allen-algebra)
 (:objects
	i1 i2 i3 i4 i5 i6 - interval
 )
 (:init
	(not-started i1)
	(not-ended i1)
	(not-started i2)
	(not-ended i2)
	(not-started i3)
	(not-ended i3)
	(not-started i4)
	(not-ended i4)
	(not-started i5)
	(not-ended i5)
	(not-started i6)
	(not-ended i6)
	(= (length i1) 5)
	(= (length i2) 11)
	(= (length i3) 5)
	(= (length i4) 5)
	(= (length i5) 11)
	(= (length i6) 5)
 )
 (:goal
	(and
		(starts i1 i2)
		(finishes i3 i2)
		(starts i4 i5)
		(finishes i6 i5)
	)
 )
)
